### ISSUE TITLE
Error in rclipboardSetup in 	Prostar1.30.3

### ISSUE THREAD

**Issue by fgarciacnio** [prostarproteomics/Prostar#25]
After tryin to upgrade Prostar to the last DAPAR version the program does not start and the browser shows an error
> BiocManager::install("Prostar")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31 ucrt)
Installing package(s) 'Prostar'
trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/windows/contrib/4.2/Prostar_1.30.3.zip'
Content type 'application/zip'
![rclipboardSetup error](https://user-images.githubusercontent.com/90319981/216002126-0b420813-2176-4780-8f1b-2b1161be6177.png)
 length 3973419 bytes (3.8 MB)
downloaded 3.8 MB

package ‘Prostar’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\fgarcia\AppData\Local\Temp\RtmpusFXDQ\downloaded_packages
> library(Prostar)
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
Warning message:
In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (1.0.9)
than is installed on your system (1.0.10). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
> Prostar()
Loading required package: shiny

Listening on http://127.0.0.1:6633
Find out what's new in shinyjs:
	https://github.com/daattali/shinyjs/releases

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

Warning: Error in rclipboardSetup: could not find function "rclipboardSetup"
  77: dots_list
  76: div
  73: fluidPage
   2: shiny::runApp
   1: Prostar
![rclipboardSetup error](https://user-images.githubusercontent.com/90319981/216002194-cf1d9d70-74c8-406e-8dd5-640fb2d31740.png)

**Comment by samWieczorek** [comment]
Hi,
Yes, the packages have been upgraded on Bioconductor  and I have been waiting this to be able to upgrade the ZIp file and the docker image.
I think I will do it this afternoon or tomorrow

**Comment by fgarciacnio** [comment]
Hi Samuel.
Thanks a lot for keeping Prostar rolling. We are using Prostar (and citing your publication if the main authors agree)  in most of our workflows.  It’s impressive how much Prostar has helped us to add statistical power to our proteomics results.
Best regards
Fernando

Fernando Garcia Martinez Ph.D.
Proteomics & MS Specialist
Proteomics Unit, Spanish National Cancer Research Centre (CNIO)
Melchor Fernández Almagro 3.
E28029 MADRID, SPAIN.
Phone  +34 912246900 ext 3112
[2018-04-13 17_08_26-Document1 - Word]

**Comment by samWieczorek** [comment]
I have fixed this issue and the new version is available as well on Bioconductor as on Prostar's website : prostar-proteomics.org
I close this issue but do not not hesitate to contact me if necessary

**Comment by fgarciacnio** [comment]
Thanks a lot, Samuel
Best regards
Fernando
