### ISSUE TITLE
[BUG Prostar] logFC One versus All

### ISSUE THREAD

**Issue by AnneMarie38** [prostarproteomics/Prostar#27]
Selon le nombre de conditions dans un dataset, le calcul du logFC d'un one vs all ne se fait pas de la même manière 
j'ai essayé avec 2 datasets
4 conditions -->  logFC = moyenne(condition 1) - moyenne (all -condition 1) (à 10^-15 près)

14 conditions --> logFC calculé autrement, aucune idée comment !?

s'il n'y a que le logFC faux, je le recalcule facilement. par contre j'ai peur que la pvalue aussi soit fausse !!?? aucun moyen de le vérifier de mon côté...

d'un point de vue générale je veux bien une explication sur comment c'est censé marcher
pq sur le dataset à 4, j'ai tenté de faire un LIMMA one vs one pour mimer le one vs all :  condition 1 * 3 rep vs condition fictive 2 * 9 rep. et on ne trouve pas le même résultat en terme de pvalue qu'un one vs all classique (on trouve bien le même logFC qu'un one vs all à 10^-15 près)

en PJ les datasets utilisés (les données sont déjà loggées) et les résultats de mes différents tests
[toSamuel.xlsx](https://github.com/prostarproteomics/Prostar/files/12726110/toSamuel.xlsx)

Anne-Marie

**Comment by samWieczorek** [comment]
La version actuelle de Prostar (1.34.0) ne permet pas d'analyser un dataset de plus de 10 conditions avec Limma. Cette limite a été repoussée à 26 condtions (version 1.34.1) pour un dataset avec design plat (pas de réplicats techniques ni analytiques). Pour le moment, il n'est pas prévu d'étendre cette option pour les designs de niveau 2 et 3
