### ISSUE TITLE
[BUG Prostar] live.prostar-proteomics.org

### ISSUE THREAD

**Issue by samWieczorek** [prostarproteomics/Prostar#5]
**Describe the bug**
When I load an excel file for processing I can create it without any problem but the screen freezes when I get to the filter step. On the other hand, no problem when I load the MSnset corresponding to the same study. (I tested with old files for which I had already generated the MSnset)

**Comment by samWieczorek** [comment]
Will be fixed with the Release 3.15 of Bioconductor

**Comment by enryH** [comment]
I cannot reach the website. Is it down?
